name: app_cms_ghc
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'  # Atualizado para uma versão mínima compatível do Flutter

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.0.2
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  shared_preferences: ^2.1.0  # Pacote para armazenar dados localmente
  intl: ^0.17.0  # Pacote para formatação de datas
  firebase_core: ^3.4.1
  firebase_crashlytics: ^4.1.1
  flutter_native_splash: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.14.1"

flutter:
  uses-material-design: true

  assets:
    - assets/data/conhecimentos tecnicos.json
    - assets/data/meteorologia.json
    - assets/data/navegacao.json
    - assets/data/regulamentos.json
    - assets/data/teoria de voo.json

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  remove_alpha_ios: true
  image_path: "assets/icon/logo600X600.png"
  min_sdk_android: 24
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/logo600X600.png"
